package com.raonmate.backend.schedule.application;
import com.raonmate.backend.global.error.ResourceNotFoundException; import com.raonmate.backend.schedule.api.*; import com.raonmate.backend.schedule.domain.*; import com.raonmate.backend.workshop.domain.*; import java.time.*; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class ScheduleService {
 private final WorkshopRepository workshops; private final SchedulePlanRepository plans;
 public ScheduleResponse get(UUID id){return ScheduleResponse.from(plans.findByWorkshopId(id).orElseThrow(()->new ResourceNotFoundException("생성된 일정이 없습니다.")));}
 @Transactional public ScheduleResponse generate(UUID id){Workshop w=workshops.findById(id).orElseThrow(()->new ResourceNotFoundException("워크숍을 찾을 수 없습니다.")); SchedulePlan p=plans.findByWorkshopId(id).orElseGet(()->new SchedulePlan(w)); LocalDate d=w.getPreferredStartDate()==null?LocalDate.now().plusDays(30):w.getPreferredStartDate(); List<SchedulePlan.Item> a=new ArrayList<>(); a.add(new SchedulePlan.Item(d,LocalTime.of(10,0),LocalTime.of(11,30),"MOVE","집결 및 이동",w.getDepartureLocation()+" 출발")); a.add(new SchedulePlan.Item(d,LocalTime.of(11,30),LocalTime.of(12,30),"MEAL","점심 식사","워크숍 시작 전 점심")); a.add(new SchedulePlan.Item(d,LocalTime.of(13,0),LocalTime.of(14,30),"SESSION","오프닝 및 아이스브레이킹",w.getPurposeKeywords())); a.add(new SchedulePlan.Item(d,LocalTime.of(14,30),LocalTime.of(17,30),"ACTIVITY","팀빌딩 프로그램",w.getRequiredConditions())); if(w.getWorkshopType()==WorkshopType.OVERNIGHT){a.add(new SchedulePlan.Item(d,LocalTime.of(18,0),LocalTime.of(19,30),"MEAL","저녁 식사","네트워킹")); LocalDate d2=d.plusDays(1); a.add(new SchedulePlan.Item(d2,LocalTime.of(8,0),LocalTime.of(9,0),"MEAL","조식","아침 식사")); a.add(new SchedulePlan.Item(d2,LocalTime.of(9,30),LocalTime.of(11,0),"SESSION","워크숍 세션","목표 및 계획 수립")); a.add(new SchedulePlan.Item(d2,LocalTime.of(11,0),LocalTime.of(12,0),"SESSION","정리 및 마무리","결과 공유"));} p.replace(a); return ScheduleResponse.from(plans.save(p));}
 @Transactional public ScheduleResponse update(UUID id,ScheduleRequest r){SchedulePlan p=plans.findByWorkshopId(id).orElseThrow(()->new ResourceNotFoundException("생성된 일정이 없습니다.")); validate(r.items()); p.replace(r.items().stream().map(i->new SchedulePlan.Item(i.date(),i.startTime(),i.endTime(),i.type(),i.title(),i.description())).toList()); return ScheduleResponse.from(p);}
 private void validate(List<ScheduleRequest.Item> items){List<ScheduleRequest.Item> sorted=items.stream().sorted(Comparator.comparing(ScheduleRequest.Item::date).thenComparing(ScheduleRequest.Item::startTime)).toList(); for(int i=1;i<sorted.size();i++){var a=sorted.get(i-1);var b=sorted.get(i);if(a.date().equals(b.date())&&a.endTime()!=null&&a.endTime().isAfter(b.startTime()))throw new IllegalArgumentException("일정 시간이 서로 겹칩니다.");}}
}
